import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage` - istanbul's HTML report ships its
    // own vendored JS, which otherwise turns up as lint warnings.
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
    // Written by `next dev` for AI agents; not hand-maintained source.
    "AGENTS.md",
    "CLAUDE.md",
  ]),
]);

export default eslintConfig;
