// Canonical curriculum is bundled at build time; no runtime file or network reads.
import flashcardFiles0 from "../../../../../content/flashcards/domain-1-flashcards.json";
import flashcardFiles1 from "../../../../../content/flashcards/domain-2-flashcards.json";
import flashcardFiles2 from "../../../../../content/flashcards/domain-3-flashcards.json";
import flashcardFiles3 from "../../../../../content/flashcards/domain-4-flashcards.json";
import flashcardFiles4 from "../../../../../content/flashcards/domain-5-flashcards.json";
import flashcardFiles5 from "../../../../../content/flashcards/domain-6-flashcards.json";
export const flashcardFiles = [flashcardFiles0, flashcardFiles1, flashcardFiles2, flashcardFiles3, flashcardFiles4, flashcardFiles5];
import labs0 from "../../../../../content/labs/ansible-network.json";
import labs1 from "../../../../../content/labs/bash-scripting.json";
import labs2 from "../../../../../content/labs/docker-basics.json";
import labs3 from "../../../../../content/labs/git-basics.json";
import labs4 from "../../../../../content/labs/netconf-basics.json";
import labs5 from "../../../../../content/labs/python-data-parsing.json";
import labs6 from "../../../../../content/labs/rest-api-client.json";
export const labs = [labs0, labs1, labs2, labs3, labs4, labs5, labs6];
import exams0 from "../../../../../content/practice-exams/sample-exam-1.json";
import exams1 from "../../../../../content/practice-exams/sample-exam-2.json";
export const exams = [exams0, exams1];
import studyGuides0 from "../../../../../content/study-guides/domain-1-software-dev.json";
import studyGuides1 from "../../../../../content/study-guides/domain-2-apis.json";
import studyGuides2 from "../../../../../content/study-guides/domain-3-cisco-platforms.json";
import studyGuides3 from "../../../../../content/study-guides/domain-4-deployment-security.json";
import studyGuides4 from "../../../../../content/study-guides/domain-5-infrastructure-automation.json";
import studyGuides5 from "../../../../../content/study-guides/domain-6-network-fundamentals.json";
export const studyGuides = [studyGuides0, studyGuides1, studyGuides2, studyGuides3, studyGuides4, studyGuides5];
import blueprintData from "../../../../../content/exam-blueprint.json";
export const blueprint = blueprintData;
export const flashcards = flashcardFiles.flatMap(file => file.flashcards.map(card => ({ ...card, domain: file.domain, domainName: file.domainName, domainSlug: blueprint.domains.find(domain => domain.number === file.domain)!.slug })));
export const objectiveIds = blueprint.domains.flatMap(domain => domain.objectives.map(objective => objective.code));
export const domainSlugs = blueprint.domains.map(domain => domain.slug);
